- name: firewall - open ports 
  firewalld:
    port: "{{ kuard_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes

- name: Get the user's home directory
  shell: >
    egrep "^{{ kuard_user }}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: user_home

- name: Creates directory
  file:
    path: "{{ user_home.stdout }}/kuard/"
    state: directory
    owner: "{{ kuard_user }}"
    group: "{{ kuard_user }}"
    mode: '0755'
  become: yes
  become_user: "{{ kuard_user }}"

- name: Copy docker-compose.yml
  template:
    src: 'docker-compose.yml.j2'
    dest: "{{ user_home.stdout }}/kuard/docker-compose.yml"
    owner: "{{ kuard_user }}"
    group: "{{ kuard_user }}"
    mode: '0755'
  become: yes
  become_user: "{{ kuard_user }}"
  ignore_errors: true

- name: Start Haproxy container
  command: "{{ docker_compose_path }} -f {{ user_home.stdout }}/kuard/docker-compose.yml up -d"
  become: yes
  become_user: "{{ kuard_user }}"
  ignore_errors: true

